name: docgen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - python-multipart
      - pydantic
      - python-docx
      - python-dotenv
      - uvicorn
      - httpx
      - openai==2.15.0
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-auth
      - google-api-python-client
      - Pillow
      - email-validator
      - aiomysql
      - bcrypt==4.0.1
      - passlib==1.7.4
      - python-jose==3.3.0
      - pyjwt==2.6.0